project:
  type: book
  output-dir: ./docs

book:
  title: "Deep Reinforcement Learning"
  author:
    - name: Dr. Julien Vitay 
      email: julien.vitay@gmail.com
      url: https://julien-vitay.net
      orcid: 0000-0001-5229-2349
  
  page-navigation: true
  bread-crumbs: false

  sidebar:
    style: floating
    background: white
    tools:
      - icon: github
        href: https://github.com/vitay/deeprl

  page-footer:
    center: |
      [Creative Commons BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0). Author [Julien Vitay](mailto:julien.vitay@gmail.com)

  chapters:
    - index.qmd
    - src/0-Introduction.qmd
    - part: "**Tabular RL**"
      chapters:
        - src/1.1-Bandits.qmd
        - src/1.2-MDP.qmd
        - src/1.4-MC.qmd
        - src/1.5-TD.qmd
    - part: "**Value-based deep RL**"
      chapters:
        - src/2.1-FunctionApproximation.qmd
        - src/2.2-DeepNetworks.qmd
        - src/2.3-DQN.qmd
        - src/2.4-DQNvariants.qmd
        - src/2.5-DistributedLearning.qmd
        - src/2.6-Misc.qmd
    - part: "**Policy-gradient methods**"
      chapters:
        - src/3.1-PolicyGradient.qmd
        - src/3.2-ActorCritic.qmd
        - src/3.3-ImportanceSampling.qmd
        - src/3.4-DPG.qmd
        - src/3.5-NaturalGradient.qmd
        - src/3.6-PPO.qmd
        - src/3.7-ACER.qmd
        - src/3.8-EntropyRL.qmd
        - src/3.9-Misc.qmd
    - part: "**Model-based deep RL**"
      chapters:
        - src/4.1-ModelBased.qmd
        - src/4.2-MBMF.qmd
        - src/4.3-Planning.qmd
        - src/4.4-WorldModels.qmd
        - src/4.5-AlphaGo.qmd
        - src/4.6-Misc.qmd
    - part: "**Advanced topics**"
      chapters:
        - src/5.1-Intrinsic.qmd
        - src/5.2-Inverse.qmd
        - src/5.3-OfflineRL.qmd
        - src/5.4-Meta.qmd
        - src/5.5-Hierarchical.qmd
    - src/references.qmd

bibliography: 
    - ReinforcementLearning.bib
    - DeepLearning.bib
csl: assets/frontiers.csl

format:
  html:
    mainfont: Roboto
    theme: [lumen, "assets/webpage.scss"]
    number-sections: false
    toc: true
    smooth-scroll: true
    html-math-method: katex
    highlight-style: github
    code-line-numbers: false
    lightbox: true

