
---
title: "**Tabular RL**"
---

The first part of this book will focus on tabular reinforcement learning.


Die Verifikation von Methoden der eXplainable Artificial Intelligence (XAI) ist unabdingbar, um die Vorhersagen komplexer, undurchsichtiger Modelle des maschinellen Lernens (ML) interpretier- und nachvollziehbar zu machen und die Korrektheit der Erklärungen zu testen. Besonders in kritischen Infrastrukturen ist eine Prüfung der eingesetzten Algorithmen durch XAI-Verfahren notwendig, um das Vertrauen in diese zu stärken und deren Richtigkeit nachzuweisen. Durch die zusätzliche Bestätigung der Korrektheit der XAI-Aussagen wird dies zunehmend untermauert. Im Rahmen dieser Bachelorarbeit werden drei Modelle des ML, eine Support-Vektor-Maschine (SVM), ein Multi-Layer Perzeptron (MLP) und eine Gated Recurrent Unit (GRU), eingesetzt. Eine Anwendung dieser erfolgt auf dem von Smerdov u. a. [SME+20] vorgestellten eSports-Sensor-Datensatz, in welchem zahlreiche biometrische Attribute einzelner Spieler enthalten sind. Mit Hilfe von XAI-Methoden sollen die relevantesten Eigenschaften der einzelnen Spieler analysiert werden. Eingesetzt werden dazu Local Interpretable Model-Agnostic Explanations (LIME), Shapley Werte, Gradients, Gradients-SmoothGrad (Gradients-SG) und Layer-Wise Relevance Propagation (LRP). Deren Aussagen werden mit Hilfe verschiedener Vergleichs- und Verifikationsmetriken - die Größe der Schnittmenge der relevantesten Attribute, die Stabilität von XAI-Methoden, deren deskriptive Genauigkeit, deskriptive Spärlichkeit und maximale Sensitivität - auf ihre Richtigkeit kontrolliert. Es wird gezeigt, dass sich die Aussagen verschiedener XAI-Verfahren unterscheiden und somit eine individuelle Korrektheitsprüfung dieser notwendig ist. Da biometrische Merkmale laut Payne u. a. [PAY+23] unter Umständen einen signifikanten Aufschluss über individuelle Muster und Charakteristiken einzelner Personen geben, besteht die Annahme, dass diese durch XAI-Methoden abgebildet werden können. Schlussendlich erfolgt daher eine Wiedererkennung der Individuen ausschließlich auf Basis der erhaltenen XAI-Ergebnisse. Es kann erfolgreich bestätigt werden, dass dies in einem bestimmten Rahmen möglich ist.