# Metadata
title: Deep Reinforcement Learning
author: Julien Vitay
email: julien.vitay@informatik.tu-chemnitz.de

# List of files to include
files:
    - 0-Introduction.md
    - 1.1-BasicRL.md
    - 1.2-DeepLearning.md
    - 2-Valuebased.md
    - 3.1-PolicyGradient.md
    - 3.2-ActorCritic.md
    - 3.3-DPG.md
    - 3.4-NaturalGradient.md
    # - 4-RAM.md
    # - 5-ModelBased.md
    # - 6-Robotics.md
    - 7-Practice.md
    - 8-References.md

# Bibliography
bibliography: 
    - /home/vitay/Articles/biblio/ReinforcementLearning.bib
    - /home/vitay/Articles/biblio/DeepLearning.bib
csl: assets/apalike.csl


# CSS
css: assets/github.css
mathjax: /usr/share/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML
# mathjax: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Latex
geometry: "margin=1in" 
fontfamily: "times" 
fontsize: "11pt"
header-includes:
    - \usepackage{setspace}
    - \onehalfspacing

