project:
  type: book
  output-dir: ../docs

book:
  title: "Deep Reinforcement Learning"
  author: "Julien Vitay"
  chapters:
    - index.qmd
    - 1.1-BasicRL.qmd
    - 1.2-DeepLearning.qmd
    - 2-Valuebased.qmd
    - 3.1-PolicyGradient.qmd
    - 3.2-ActorCritic.qmd
    - 3.3-ImportanceSampling.qmd
    - 3.4-DPG.qmd
    - 3.5-NaturalGradient.qmd
    - 3.6-EntropyRL.qmd
    - 3.7-DistributionalRL.qmd
    - 3.8-OtherPolicyGradient.qmd
    - 4-RAM.qmd
    - 5-ModelBased.qmd
    - 6-Hierarchical.qmd
    - 7-Inverse.qmd
    - 8-Robotics.qmd
    - 9-Practice.qmd
    - references.qmd

bibliography: 
    - "ReinforcementLearning.bib"
    - "DeepLearning.bib"
csl: frontiers.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



